import { readFileSync, readdirSync, statSync, appendFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import { detect } from "./detect.js";
import type { Confidence, ProtocolId } from "./types.js";

export interface ScanEntry {
  path: string;
  protocol: ProtocolId;
  version?: string;
  confidence: Confidence;
  reason: string;
}

export interface RunnerEnv {
  inputs: Record<string, string | undefined>;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  /** Walk dir + return JSON file paths. Defaults to fs.readdirSync recursive walk. */
  walk?: (dir: string) => string[];
  /** Read a file from disk. Defaults to fs.readFileSync. */
  readFile?: (path: string) => string;
  /** Predicate: does this path exist? Defaults to fs.existsSync. */
  exists?: (path: string) => boolean;
  /** Stubbed PR-comment poster for tests. */
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  /** Output stream. */
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  entries: ScanEntry[];
  unknownCount: number;
  commentPosted: boolean;
  reason?: string;
}

const CONFIDENCE_RANK: Record<Confidence, number> = { low: 0, medium: 1, high: 2 };

function defaultWalk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      out.push(...defaultWalk(p));
    } else if (st.isFile() && p.toLowerCase().endsWith(".json")) {
      out.push(p);
    }
  }
  return out;
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const scanDir = required(env.inputs, "scan_dir");
  const failOnUnknown = (env.inputs.fail_on_unknown ?? "false").toLowerCase() === "true";
  const minConfidence = (env.inputs.min_confidence ?? "low").toLowerCase() as Confidence;
  if (!(minConfidence in CONFIDENCE_RANK)) {
    throw new Error(`input "min-confidence" must be one of "high", "medium", "low" — got "${minConfidence}"`);
  }
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const token = env.inputs.github_token ?? "";

  const walk = env.walk ?? defaultWalk;
  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const exists = env.exists ?? ((p) => existsSync(p));
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  if (!exists(scanDir)) {
    write(`::error::scan-dir "${scanDir}" does not exist on disk.`);
    return { exitCode: 1, entries: [], unknownCount: 0, commentPosted: false, reason: "scan-dir not found" };
  }

  const files = walk(scanDir);
  const entries: ScanEntry[] = [];
  for (const path of files) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(read(path));
    } catch (e) {
      entries.push({ path, protocol: "unknown", confidence: "low", reason: `JSON parse failed: ${(e as Error).message}` });
      continue;
    }
    const result = detect(parsed);
    entries.push({ path, protocol: result.protocol, version: result.version, confidence: result.confidence, reason: result.reason });
  }

  const minRank = CONFIDENCE_RANK[minConfidence];
  const unknownCount = entries.filter(
    (e) => e.protocol === "unknown" || CONFIDENCE_RANK[e.confidence] < minRank
  ).length;

  const summary = renderSummary(entries, scanDir);
  setOutput(env, "file-count", String(entries.length));
  setOutput(env, "unknown-count", String(unknownCount));
  setOutput(
    env,
    "summary-json",
    JSON.stringify(entries.map((e) => ({ path: e.path, protocol: e.protocol, version: e.version, confidence: e.confidence })))
  );

  write(`\n${summary}\n`);

  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `### Kinetic Gain Protocol Detect — \`${scanDir}\`\n\n${summary}\n\n_Generated by [kg-protocol-detect-action](https://github.com/mizcausevic-dev/kg-protocol-detect-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (failOnUnknown && unknownCount > 0) {
    write(`::error::${unknownCount} of ${entries.length} JSON files failed protocol detection (or below min-confidence=${minConfidence}).`);
    return { exitCode: 1, entries, unknownCount, commentPosted, reason };
  }

  return { exitCode: 0, entries, unknownCount, commentPosted, reason };
}

function renderSummary(entries: ScanEntry[], scanDir: string): string {
  if (entries.length === 0) return `_No JSON files found under \`${scanDir}\`._`;
  const buckets = new Map<ProtocolId, ScanEntry[]>();
  for (const e of entries) {
    const arr = buckets.get(e.protocol) ?? [];
    arr.push(e);
    buckets.set(e.protocol, arr);
  }
  const lines: string[] = [`Scanned **${entries.length}** JSON file(s) under \`${scanDir}\`.`, ""];
  lines.push("| Protocol | Count |");
  lines.push("|---|---|");
  for (const [protocol, arr] of buckets) {
    lines.push(`| \`${protocol}\` | ${arr.length} |`);
  }
  return lines.join("\n");
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
